version: "3.5"
# define all services
services:
  caiena.front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:8080"
    volumes:
      - .:/app:cached
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
